disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
included:
  - Sources
  - Tests
excluded:
  - .build
  - .swiftpm
  - DerivedData
  - dist
  - node_modules
  - platforms
  - modules
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
function_body_length:
  warning: 50
  error: 100
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 300
  error: 500
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - to
reporter: "xcode"
