name: DOJO-suite

options:
  bundleIdPrefix: com.nexusinfinity.dojo
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
  xcodeVersion: "15.0"
  
settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  DOJOShared:
    type: framework
    platform: [iOS, macOS]
    sources:
      - path: Sources/DOJOShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nexusinfinity.dojo.DOJOShared
        SUPPORTS_MACCATALYST: false
        GENERATE_INFOPLIST_FILE: true
        DEFINES_MODULE: true
    scheme:
      testTargets:
        - DOJOSharedTests

  DOJOiOSApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/DOJOiOSApp
    dependencies:
      - target: DOJOShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nexusinfinity.dojo.DOJOiOSApp
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    scheme:
      testTargets:
        - DOJOSharedTests

  DOJOMacApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/DOJOMacApp
    dependencies:
      - target: DOJOShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nexusinfinity.dojo.DOJOMacApp
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 nexus-infinity. All rights reserved."
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
    scheme:
      testTargets:
        - DOJOSharedTests

  DOJOSharedTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    sources:
      - path: Tests/DOJOSharedTests
    dependencies:
      - target: DOJOShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nexusinfinity.dojo.DOJOSharedTests
        GENERATE_INFOPLIST_FILE: true
