'use client'

import { useState } from 'react'
import { SpellCircle } from './SpellCircle'

// Code/Artifact panel — split view like Claude's artifact window.
// Left: conversation with code-generating instructions.
// Right: live artifact (code viewer, preview, diff).

type ArtifactType = 'code' | 'html' | 'svg' | 'markdown'

interface Artifact {
  id: string
  type: ArtifactType
  title: string
  language?: string
  content: string
  chamber: string
}

const SAMPLE_ARTIFACT: Artifact = {
  id: 'intro',
  type: 'code',
  title: 'Chamber health check',
  language: 'typescript',
  chamber: 'dojo',
  content: `// ◼︎ DOJO — chamber health check
// Generated by NIAMA  741 Hz

const CHAMBERS = {
  dojo:   { port: 7410, symbol: '◼︎' },
  obiwan: { port: 9630, symbol: '●'  },
  atlas:  { port: 5280, symbol: '▲'  },
  tata:   { port: 4320, symbol: '▼'  },
  akron:  { port: 3960, symbol: '◻'  },
} as const

async function checkAll() {
  const results = await Promise.allSettled(
    Object.entries(CHAMBERS).map(async ([name, { port, symbol }]) => {
      const res = await fetch(\`http://localhost:\${port}/health\`)
      const json = await res.json()
      return { name, symbol, port, ...json }
    })
  )
  results.forEach(r => {
    if (r.status === 'fulfilled') {
      console.log(\`\${r.value.symbol} \${r.value.name}  :\${r.value.port}  ✓\`)
    }
  })
}

checkAll()`,
}

export function CodeArtifact() {
  const [artifact, setArtifact] = useState<Artifact>(SAMPLE_ARTIFACT)
  const [activeTab, setActiveTab] = useState<'code' | 'preview'>('code')
  const [copied, setCopied] = useState(false)

  async function copy() {
    await navigator.clipboard.writeText(artifact.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="flex h-full">

      {/* Left — instructions pane */}
      <div className="w-80 shrink-0 border-r border-border flex flex-col bg-surface">
        <div className="px-4 py-3 border-b border-border">
          <h2 className="text-sm font-semibold text-slate-300">Code workspace</h2>
          <p className="text-xs text-muted mt-0.5">Ask NIAMA to generate, refactor, or explain code</p>
        </div>

        <div className="flex-1 p-4 space-y-3 overflow-y-auto">
          {/* Prompt examples */}
          {[
            'Generate a Swift MCP client for DOJO :7410',
            'Write a Python health check for all chambers',
            'Create a Next.js API route for streaming chat',
            'Translate ARKADASHomeView.swift to React',
            'Write a MLX LoRA training config for GPT-OSS-20B',
          ].map(prompt => (
            <button
              key={prompt}
              className="w-full text-left text-xs text-muted hover:text-slate-300 px-3 py-2.5 rounded-lg bg-raised hover:bg-border transition-colors leading-snug"
            >
              {prompt}
            </button>
          ))}
        </div>

        <div className="p-3 border-t border-border">
          <div className="flex items-center gap-2 text-xs text-dim font-mono">
            <SpellCircle chamber="dojo" size={16} compact />
            <span>◼︎ 741 Hz</span>
          </div>
        </div>
      </div>

      {/* Right — artifact viewer */}
      <div className="flex-1 flex flex-col min-w-0">

        {/* Artifact header */}
        <div className="flex items-center justify-between px-4 py-2.5 border-b border-border bg-surface shrink-0">
          <div className="flex items-center gap-3">
            <SpellCircle chamber={artifact.chamber as any} size={20} compact />
            <span className="text-sm font-medium text-slate-200">{artifact.title}</span>
            {artifact.language && (
              <span className="text-xs font-mono text-dojo bg-dojo/10 px-2 py-0.5 rounded">{artifact.language}</span>
            )}
          </div>

          <div className="flex items-center gap-2">
            {/* View tabs */}
            <div className="flex gap-1 bg-raised rounded-lg p-0.5">
              {(['code', 'preview'] as const).map(tab => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-1 rounded text-xs font-medium transition-all ${
                    activeTab === tab ? 'bg-surface text-slate-200' : 'text-muted hover:text-slate-300'
                  }`}
                >
                  {tab === 'code' ? '⟨/⟩ Code' : '⬡ Preview'}
                </button>
              ))}
            </div>

            <button
              onClick={copy}
              className="text-xs text-muted hover:text-slate-300 px-2 py-1 rounded transition-colors"
            >
              {copied ? '✓ Copied' : 'Copy'}
            </button>
          </div>
        </div>

        {/* Code view */}
        {activeTab === 'code' && (
          <div className="flex-1 overflow-auto">
            <pre className="p-6 text-sm font-mono text-slate-200 leading-relaxed min-h-full">
              <code>{artifact.content}</code>
            </pre>
          </div>
        )}

        {/* Preview — renders HTML artifacts */}
        {activeTab === 'preview' && (
          <div className="flex-1 overflow-auto bg-white">
            {artifact.type === 'html'
              ? <iframe srcDoc={artifact.content} className="w-full h-full border-0" title="Preview" />
              : <div className="flex items-center justify-center h-full bg-raised">
                  <p className="text-muted text-sm">Preview available for HTML artifacts</p>
                </div>
            }
          </div>
        )}
      </div>
    </div>
  )
}
